### ISSUE TITLE
Example to get current MIR trading value

### ISSUE THREAD

**Issue by sourabhlk** [Mirror-Protocol/docs#6]
HI.. 
Can you provide some examples on how to retrieve current trading value of MIR protocol value.. using rest api
Thanks

**Comment by jeelimm** [comment]
You can use https://graph.mirror.finance/graphql 

If you do: 
query {
  asset(token:"terra15gwkyepfc6xgca5t5zefzwy42uts8l2m4g40k6"){
    status
    prices {
      price
    }
    statistic {
      volume(network:TERRA)
      }
    }
  }
It will return both MIR Price and Volume (24h). 
Also this issue should be submitted on mirror-graph, thus closing the issue.
