### ISSUE TITLE
query returning wrong values

### ISSUE THREAD

**Issue by sourabhlk** [Mirror-Protocol/docs#7]
Hi.. 
Tried 
curl -X POST -H "Content-Type: application/json" -d '{"query": "{ assets { symbol prices { price } } }"}' https://tequila-graph.mirror.finance/graphql

to get prices of assets but returning

{"data":{"assets":[{"symbol":"MIR","prices":{"price":"0.371516"}},{"symbol":"mBTC","prices":{"price":"58203.121412"}},{"symbol":"mETH","prices":{"price":"1804.019515"}},{"symbol":"mDIS","prices":{"price":null}},{"symbol":"mAAPL","prices":{"price":"120.830316"}},{"symbol":"mABNB","prices":{"price":"203.911017"}},{"symbol":"mAMC","prices":{"price":"13.144914"}},{"symbol":"mAMZN","prices":{"price":"2929.558041"}},{"symbol":"mBABA","prices":{"price":"235.874519"}},{"symbol":"mFB","prices":{"price":"282.823791"}},{"symbol":"mGME","prices":{"price":"207.425814"}},{"symbol":"mGOOGL","prices":{"price":"1973.611675"}},{"symbol":"mGS","prices":{"price":"331.043890"}},{"symbol":"mIAU","prices":{"price":"17.257208"}},{"symbol":"mMSFT","prices":{"price":"238.563719"}},{"symbol":"mNFLX","prices":{"price":"501.661317"}},{"symbol":"mQQQ","prices":{"price":"320.975558"}},{"symbol":"mSLV","prices":{"price":"24.935076"}},{"symbol":"mTSLA","prices":{"price":"672.190559"}},{"symbol":"mTWTR","prices":{"price":"67.733921"}},{"symbol":"mUSO","prices":{"price":"42.101168"}},{"symbol":"mVIXY","prices":{"price":"11.078949"}}]}}

MIR price is was around 6.77 but in response showing 0.371516

**Comment by jeelimm** [comment]
This issue is specific to mirror-graph: https://github.com/Mirror-Protocol/mirror-graph/issues
